### PR TITLE
Acknowledge Outreachy interns

### PR DESCRIPTION
**Pull request by sgibson91**
I thought it would be nice to acknowledge our Outreachy interns in our team compass to raise the profile of this kind of work across the team.

I've added a script that generates a grid of contributors cards and then embeds them into the team page. Happy to move things around if folk think this belongs somewhere else in the docs.

### CODE REVIEW

**Review by consideRatio — APPROVED** [review]
I just glanced quickly, but this LGTM!

Thank you soo much @sgibson91 for doing this work!!!!

**Review by minrk — APPROVED** [review]

**Comment by choldgraf** [comment]
Two quick thoughts, though I don't think either need to block:

1. Is there any chance we could store the data in YAML and then convert to JSON before passing through the schema? That would match our other data format types.
2. Could we add @GeorgianaElena and @leportella, our first two Outreachy interns? (❤️)

**Comment by sgibson91** [comment]
> 1. Is there any chance we could store the data in YAML and then convert to JSON before passing through the schema? That would match our other data format types.

I went with json, because I didn't want to have to think too hard about the key name for each cohort 😅 I did originally start in yaml, but felt `cohort_dec22` as a top level key was messy

**Comment by choldgraf** [comment]
(sounds good re: JSON, I don't think it's a huge deal so happy w/ whatever)

**Comment by sgibson91** [comment]
Ok, I've added Georgiana and Leticia, so I will go for a merge!

**Pull request merged**
