### PR TITLE
adding codecov to team compass

### PR DESCRIPTION
**Pull request by choldgraf**
Adds code coverage badges for the repositories we had listed to team compass, also adds kubespawner

### CODE REVIEW

**Comment by betatim** [comment]
This is a great idea!

Screen Shot 2019-04-04 at 22 06 30

My inner tidyness geek dislikes the changing size of the badges though, also super hard to read the small ones. How many favours do I owe you if I ask if we can rotate the table so that a project is a row instead of a column?

**Comment by choldgraf** [comment]
lol tim you're killing me here, lemme see if I can do this with a pandas transpose :-)

**Comment by choldgraf** [comment]
wohooo! thank god for pandas

image

**Comment by betatim** [comment]
You learnt a new pandas skill and how much nicer does this look? Exactly, about 10x nicer!

**Comment by betatim** [comment]
Also, all that hard work on getting repo2docker coverage up is paying dividends. Not only are we "in the lead" in this table but without it we would be in deep trouble with making changes to r2d at the scale that we are. Kudos to everyone who helped make it so!

**Pull request merged**
