### PR TITLE
Switching to pandas theme

### PR DESCRIPTION
**Pull request by choldgraf**
Recently @jorisvandenbossche showed off a really nice-looking theme from the Pandas community, that was also adopted by the Bokeh community. This is a PR to demo what this theme looks like for our team-compass docs so we can get a feel for its structure / style / configuration.

To make this work, I had to add an "index" page that is the landing page for each of our `toctree` sections, and then within this page I linked out to the pages that are within that section (rather than having the toctree for the whole site defined in `index.rst`, it is now split over a few pages).

I also updated the logo to fit the new layout (which is probably a good idea since the old one breaks the Jupyter design instructions 😬)

Here's a demo of what it looks like

https://164-113493831-gh.circle-artifacts.com/0/html/index.html

would love to hear opinions!

(my 2 cents is that I think this is a much cleaner layout. If we wanted to use something like this, we may want to re-organize a little bit, but IMO it'll help reduce the cognitive load that many of our more complex docs pages have.)

### CODE REVIEW

**Comment by choldgraf** [comment]
would love to hear what @willingc thinks :-)

**Comment by meeseeksmachine** [comment]
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/bokeh-has-a-new-docs-template/2548/3

**Comment by willingc** [comment]
Go for it @choldgraf

**Comment by choldgraf** [comment]
OK, I made a few upstream improvements to the pandas sphinx theme and re-built these docs, and I think this one is ready to merge if folks are +1 on it now

**Comment by betatim** [comment]
LGTM

**Comment by betatim** [comment]
Merged. I am not a huge fan of "jupyterHub" somehow feels like we are going back in time to a design that should have been forgotten like `<blink>` tags. Can we make the J a capital J again not a lowercase j? Maybe it already is an upper case letter but the way it looks, it looks like it is lower case. or maybe go for jupyterhub with everything lower case?

**Comment by choldgraf** [comment]
@betatim - oops good call, I agree that a lowercase H is better. I don't think we can change the J because that'd be changing the jupyter logo, no?

https://github.com/jupyterhub/team-compass/pull/222

**Comment by Zsailer** [comment]
This page looks great @choldgraf! 🎉

**Pull request merged**
