### PR TITLE
Add March meeting minutes

### LINKED ISSUE #264: March Team Meeting 2020
Hello everyone, 

Reminder that our next meeting is **Thursday, March 19th, 2020** at 5PM UTC (or your [timezone](https://arewemeetingyet.com/UTC/2020-03-19/17:00/JupyterHub%20Binder%20team%20meeting)). 

* You can find the agenda [here](https://hackmd.io/u2ghJJUCRWK-zRidCFid_Q?both).
* And we'll meet on Zoom (video conferencing) [here](https://calpoly.zoom.us/my/jupyter)

These calls are open to **anyone**, so please join us! We love seeing new members on the call.

### PR DESCRIPTION
**Pull request by sgibson91**
fix #264

### CODE REVIEW

**Comment by betatim** [comment]
We need a fix similar to https://github.com/jupyter/repo2docker/pull/816 here as well

**Comment by choldgraf** [comment]
done - @sgibson91 wanna rebase?

**Comment by sgibson91** [comment]
@choldgraf done!

**Comment by choldgraf** [comment]
woo, thanks!

**Pull request merged**
