### PR TITLE
Transition to MyST using rst2myst (that did all the work)

### PR DESCRIPTION
**Pull request by consideRatio**
## rST to MyST conversion

I tried out [rst2myst](https://github.com/executablebooks/rst-to-myst) again, and at this time its producing really really good results! I didn't observe anything that was needed to be done besides things that was probably incorrect in the rST itself.

```shell
$ pip install rst2myst
...

$ rst2myst convert --replace-files --raise-on-warning docs/**/*.rst

docs/binder/subdomains.rst -> docs/binder/subdomains.md
CONVERTED (extensions: [])
docs/governance.rst -> docs/governance.md
CONVERTED (extensions: [])
docs/index.rst -> docs/index.md
CONVERTED (extensions: [])
docs/index-team_guides.rst -> docs/index-team_guides.md
CONVERTED (extensions: [])
docs/index-team_policies.rst -> docs/index-team_policies.md
CONVERTED (extensions: [])
docs/meetings/community/index.rst -> docs/meetings/community/index.md
CONVERTED (extensions: [])
docs/meetings/hpc/index.rst -> docs/meetings/hpc/index.md
CONVERTED (extensions: [])
docs/practices/adding-members.rst -> docs/practices/adding-members.md
CONVERTED (extensions: [])
docs/practices/talking.rst -> docs/practices/talking.md
CONVERTED (extensions: [])
docs/resources/milestones.rst -> docs/resources/milestones.md
CONVERTED (extensions: ['colon_fence'])
docs/team/index.rst -> docs/team/index.md
CONVERTED (extensions: [])

FINISHED ALL! (extensions: ['colon_fence'])
```

## Small fixes

Note the small fixes I also made in three other small commits as well when reviewing this PR.

### CODE REVIEW

**Comment by manics** [comment]
rst2myst sounds cool! How thoroughly does this (and other PRs like https://github.com/jupyterhub/kubespawner/pull/684) need to be reviewed- does the generated content need to be checked, or can we assume it's fine if there are no build errors?

**Comment by consideRatio** [comment]
@manics I think we need to gain experience to learn how thoroughly we need to review things like this. I don't know that the transformation can be guaranteed to be exactly the same or similar.

So far though, I've only reacted to a few sphinx directive not being transitioned to myst markdown as an issue. So, there has been some eval-rst statements etc that I've manually transitioned to be pure MyST.

**Review by choldgraf — APPROVED** [review]
My personal feeling is that we should just go for it. I really like MyST markdown and find it easier to remember and maintain than rST, probably also easy for others out there to learn as well.

For this PR, I'm +1 on merging as long as @consideRatio suggests there weren't any bugs he noticed.

From a team process perspective, I think we should:

1. Decide if MyST Markdown is a "recommended" standard for our documentation, via a `Documentation standards` addition to our team policies section.
2. If so, then assume that any PR to convert rST to MyST is welcome, and reviews should focus on implementation errors rather than the decision.
3. When those PRs pop up, we should merge them relatively quickly because they'll become out of date quickly as well. (similar to `black`).

**Review by GeorgianaElena — APPROVED** [review]
I am +1 on this transition. Thanks @consideRatio 

> Decide if MyST Markdown is a "recommended" standard for our documentation, via a Documentation standards addition to our team policies section.

I feel like MyST Markdown already functions like the "recommended standard" across jupyterhub repositories, since many repos transitioned to it already. We just need to make this practice explicit. Adding it to the  team policies section seems like a good place to start.

> does the generated content need to be checked, or can we assume it's fine if there are no build errors?

I believe fixing any left over small bugs from [rst2myst](https://github.com/executablebooks/rst-to-myst) might be less of a work than manually migrating the files.
My personal opinion about the approach to take when reviewing these kind of PRs is to:
- go through the files and see if anything wrong obviously stands out
- if not and no build errors, then merge
- fix any bugs we spot or get reported when/if they come up afterwards

**Comment by minrk** [comment]
👍 agreed PRs for this would be welcome by me anywhere we still have rst.

**Review by minrk — APPROVED** [review]

**Comment by consideRatio** [comment]
Thanks for the review!

- Note that we also have #350 about myst/rst

**Pull request merged**
