### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### jupyterhub/team-compass now has a Chat Room on Gitter

@yuvipanda has just created a chat room. You can visit it here: [https://gitter.im/jupyterhub/random](https://gitter.im/jupyterhub/random?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/jupyterhub/random?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://gitlab.com/gitlab-org/gitter/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by manics** [comment]
Bots talking to bots....

**Comment by yuvipanda** [comment]
I'm not sure if we should do this, since it makes it look like the 'official' chat for team-compass, which isn't what I intended.

**Comment by choldgraf** [comment]
I also don't know if it's a great idea but I fear that we will trigger the robot uprising if we deny both bots at once...

**Comment by betatim** [comment]
Closed because we have several chat rooms already. What is the goal of the new one (and it seems like it is called "random" so how did the robot figure out to create a badge here?)

**Comment by sgibson91** [comment]
New one is for gossip 😉

**Pull request closed without merging**
